### ISSUE TITLE
Spheres are drawn after disabling and reloading save

### ISSUE THREAD

**Issue by Wolvereness** [StrikeForceZero/KSP-OrbitPOInts#3]
When a save is loaded, spheres are drawn again, even when disabled before loading.

**Comment by Wolvereness** [comment]
![image](https://github.com/StrikeForceZero/KSP-OrbitPOInts/assets/983111/f91de7e5-8ab6-47cb-8027-2b91b3063955)
This screenshot should demonstrate the issue.

**Comment by StrikeForceZero** [comment]
Fixed with v0.2.1.0 

specifically https://github.com/StrikeForceZero/KSP-OrbitPOInts/commit/a6554d2285cbdceba8923817cbcdc5bf3f91cffe
